export function sendText(config)
export function sendPhoneCall(phoneNumber, phoneAppOnly)
export function sendPhoneDial(phoneNumber, phoneAppOnly = false)
export function sendSms(phoneNumber, body = null)
export function addCalendarEvent(config)
export function isAppInstalled(packageName)
export function installRemoteApp(uri, saveAs)
export function openCalendar()
export function sendMail(mail, subject = "", body = "")
export function openChooserWithOptions(options, title)
export function openChooserWithMultipleOptions(options, title)
export function openMaps(query)
export function openCamera()
export function openMapsWithRoute(query, mode)
export function shareTextToLine(options)
export function shareImageToInstagram(type, mediaPath)
export function openSettings(settingsName)
export function getVoiceMailNumber()
export function getPhoneNumber()
export function openApp(packageName: string, extras: { [index: string]: string })
export function openAppWithData(packageName: string, dataUri: string, mimeType?: string, extras?: { [index: string]: string })
export function openWebIntent(dataUri: string)
export function openFileChooser(options, title)
